### ISSUE TITLE
Invoke wsfunction

### ISSUE THREAD

**Issue by ElModdy** [lukecarr/joodle#7]
Hi, I'm trying to fetch my courses using `core_enrol_get_users_courses`.
I tried using the following code
```js
import { Client } from "joodle";

const client = new Client({
  baseURL: "https://elearning.dm.unipi.it",
  token: "mytoken",
});

(async () => {
  try {
    const courses = await client.invoke("core_enrol_get_users_courses",{
        userid: "myuserid"
    });
    console.log(courses)
  } catch (error) {
    console.error(error)
  }
})();
```
but seems like `Client` class is not exported by your module and I also have no idea how to pass the parameters.
I really appreciate any kind of help.

**Comment by lukecarr** [comment]
`Client` is an abstract class, `Joodle` is the exported implementation of `Client` that you need to use.

Taking your code, it would need to look something like this:

```js
import { Joodle } from "joodle";

const client = new Joodle({
  baseURL: "https://elearning.dm.unipi.it",
  token: "mytoken",
});

// ... use `client` here
```

Let me know if you need anything else!
